<?php

/**
 * The very first thing you need to do, is to register your app over at put.io
 * You can do that here: https://put.io/v2/oauth2/register
 *
 * Once your app is registered, users now can give it permission to access their data.
 * They only need to give your app permission once. You can request it like this:
 *
**/

$clientID = 1234; // Your own client ID
$redirectURI = 'http://example.com/callback.php'; // Your callback URI.

require '../PutIO.php';

$putio = new PutIO();
$putio->oauth->requestPermission($clientID, $redirectURI);

/**
 * The above code will redirect the user to put.io and request their permission to
 * access their data. If they approve of your app, they will be redirected to the URL
 * you specified while registering your app. In my example case, it's 'callback.php'
 *
 * In callback.php, you have to verify the code by doing something similar to this:
 *
**/

$clientID = 1234; // Your own client ID
$redirectURI = 'http://example.com/callback.php'; // Your callback URI.
$code = $_GET['code']; // A random code generated by put.io

require '../PutIO.php';

$putio = new PutIO();

if ($accessToken = $putio->oauth->verifyCode($clientID, $redirectURI, $code))
{
    // Success! Save $accessToken somewhere safe! You need it for all further requests in the future.
}
else
{
    // Something failed. Try again?
}

/**
 * Once you have the access token, you can save and keep it. It'll be enough for future API requests.
 * Take a look at the other examples for further information.
 *
**/

?>